#ifndef CONFIG_H
#define CONFIG_H
#define KERNEL_CODE_SELECTOR 0x08
#define KERNEL_DATA_SELECTOR 0x10

#define VARGOOS_TOTAL_INTERRUPTS 512
#define VARGOOS_HEAP_SIZE_BYTES 104857600 //100 megabytes in bytes
#define VARGOOS_HEAP_BLOCK_SIZE 4096
#define VARGOOS_HEAP_ADDRESS 0x01000000
#define VARGOOS_HEAP_TABLE_ADDRESS 0x00007E00 // 480.5 KiB

#define VARGOOS_SECTOR_SIZE 512

#define VARGOOS_MAX_FILESYSTEMS 12
#define VARGOOS_MAX_FILE_DESCRIPTORS 512
#define VARGOOS_TOTAL_GDT_SEGMENTS 6
#define VARGOOS_MAX_PROGRAM_ALLOCATIONS 1024
#define VARGOOS_MAX_PATH 108
#define VARGOOS_MAX_PROCESSES 12

#define VARGOOS_PROGRAM_VIRTUAL_ADDRESS 0x400000
#define VARGOOS_USER_PROG_STACK_SIZE (1024 * 16) // 16 KiB
#define VARGOOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START 0x3FF000
#define VARGOOS_PROGRAM_VIRTUAL_STACK_ADDRESS_END (VARGOOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START - VARGOOS_USER_PROG_STACK_SIZE)
#define USER_DATA_SEGMENT 0x23
#define USER_CODE_SEGMENT 0x1b

#endif
